from random import randint


from konlpy.tag import Kkma
from konlpy.utils import pprint


# Char level augmentation
# DECORATOR IMPLEMENTATION
def replace_char(sentence, distribution, ratio=0.1, safe_checker=None):
    len_sentence = len(sentence)
    num_operation = int(len_sentence*ratio)
    for i in range(num_operation):
        # LOOKS TOO SLOW
        pos = randint(0, len_sentence-1)
        sentence = sentence[:pos-1] + distribution.get_one() + sentence[pos:]
    return sentence

def insert_char(sentence, distribution, ratio=0.1, safe_checker=None):
    len_sentence = len(sentence)
    num_operation = int(len_sentence*ratio)
    for i in range(num_operation):
        # LOOKS TOO SLOW
        pos = randint(0, len_sentence-1)
        sentence = sentence[:pos] + distribution.get_one() + sentence[pos:]
    return sentence

def omit_char(sentence, ratio=0.1, safe_checker=None):
    len_sentence = len(sentence)
    num_operation = int(len_sentence*ratio)
    for i in range(num_operation):
        # LOOKS TOO SLOW
        pos = randint(0, len_sentence-1)
        sentence = sentence[:pos-1] + sentence[pos:]
    return sentence

def swap_char(sentence, ratio=0.1, safe_checker=None):
    len_sentence = len(sentence)
    num_operation = int(len_sentence*ratio)
    for i in range(num_operation):
        # LOOKS TOO SLOW
        pos_1 = randint(0, len_sentence-1)
        pos_2 = randint(0, len_sentence-1)
        # sentence = sentence[:pos_1] + sentence[pos:]
    return sentence

kkma = Kkma()

# Word/Pos level augmentation
def replace_word(sentence):
    # split each sentence into chunks
    pprint(kkma.sentences(sentence))

    # randomly select a word to replace

    # insert a new word generated by joint probability to a replaced position
    
    # return newly created sentence
    pass

def insert_word(sentence):
    # split each sentence into chunks

    # randomly select a position to insert a new word

    # insert a new word generated by joint probability

    # return newly created sentence
    pass

def omit_word(sentence):
    # split each sentence into chunks

    # randomly select a word to replace

    # return newly created sentence
    pass

def swap_word(sentence):
    # split each sentence into chunks

    # randomly select two words to swap

    # return newly created sentence

    pass
